name: Production CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Download code onto the GitHub server
      - name: Checkout Code
        uses: actions/checkout@v4

        # checking if there is a unclosed tag or typo in a tag
      - name: HTML Syntax Checking
        run: |
          npm install -g htmlhint
          htmlhint index.html


      - name: Check for broken links
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          # it tells the checker to look specifically at HTML file and ignore social media links 
          args: '--exclude "instagram\.com" --exclude "twitter\.com" --exclude "linkedin\.com" ./index.html'
          #it forces the pipeline to turn red and stop if a dead link is found
          fail: true

      # installing Netlify Command Line Interface
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: netlify deploy --prod --dir=.